### ISSUE TITLE
update for 3.15?

### ISSUE THREAD

**Issue by N4Z1T** [veenarm/TradeMaster_POE#8]
really love and grateful for work you done on this beast little apps. hope you can update for 3.15. thanks alot! my life not complete without this tools

**Comment by veenarm** [comment]
Knew i forgot something.. I'll fix it tonight.
Wasn't sure it was still used anymore.

Ill look to make a new version that auto updates league from Poe ninja or something as well.

**Comment by N4Z1T** [comment]
thanks you so much!

**Comment by veenarm** [comment]
Apologies it took so long :( prob too late now, but it's been updated,.
I need to update it to auto get this value so i no longer have to manage it :) will mark it as a issue

**Comment by veenarm** [comment]
updated for scourge
